/* AUTO-GENERATED by codegen/parse_headers.py */
/* Server-side dynamic dispatch for ALL CUDA library functions */

#include <dlfcn.h>
#include <cstdio>
#include <cstring>
#include <unordered_map>
#include <string>

/* Function registry: maps function name -> dlsym'd pointer */
static std::unordered_map<std::string, void*> g_func_cache;

static void* g_lib_cublas = nullptr;
static void* g_lib_cublasLt = nullptr;
static void* g_lib_cuda_driver = nullptr;
static void* g_lib_cuda_runtime = nullptr;
static void* g_lib_cudnn = nullptr;
static void* g_lib_cufft = nullptr;
static void* g_lib_curand = nullptr;
static void* g_lib_cusolverDn = nullptr;
static void* g_lib_cusparse = nullptr;
static void* g_lib_nvjpeg = nullptr;
static void* g_lib_nvrtc = nullptr;

void init_all_cuda_libs() {
    if (!g_lib_cuda_runtime) g_lib_cuda_runtime = dlopen("libcudart.so", RTLD_NOW | RTLD_GLOBAL);
    if (!g_lib_cuda_driver) g_lib_cuda_driver = dlopen("libcuda.so", RTLD_NOW | RTLD_GLOBAL);
    if (!g_lib_cublas) g_lib_cublas = dlopen("libcublas.so", RTLD_NOW | RTLD_GLOBAL);
    if (!g_lib_cublasLt) g_lib_cublasLt = dlopen("libcublasLt.so", RTLD_NOW | RTLD_GLOBAL);
    if (!g_lib_cudnn) g_lib_cudnn = dlopen("libcudnn.so", RTLD_NOW | RTLD_GLOBAL);
    if (!g_lib_cufft) g_lib_cufft = dlopen("libcufft.so", RTLD_NOW | RTLD_GLOBAL);
    if (!g_lib_cusparse) g_lib_cusparse = dlopen("libcusparse.so", RTLD_NOW | RTLD_GLOBAL);
    if (!g_lib_cusolverDn) g_lib_cusolverDn = dlopen("libcusolver.so", RTLD_NOW | RTLD_GLOBAL);
    if (!g_lib_curand) g_lib_curand = dlopen("libcurand.so", RTLD_NOW | RTLD_GLOBAL);
    if (!g_lib_nvrtc) g_lib_nvrtc = dlopen("libnvrtc.so", RTLD_NOW | RTLD_GLOBAL);
    if (!g_lib_nvjpeg) g_lib_nvjpeg = dlopen("libnvjpeg.so", RTLD_NOW | RTLD_GLOBAL);
}

void* resolve_cuda_function(const char* name) {
    auto it = g_func_cache.find(name);
    if (it != g_func_cache.end()) return it->second;
    init_all_cuda_libs();
    void* fn = nullptr;
    if (!fn && g_lib_cublas) fn = dlsym(g_lib_cublas, name);
    if (!fn && g_lib_cublasLt) fn = dlsym(g_lib_cublasLt, name);
    if (!fn && g_lib_cuda_driver) fn = dlsym(g_lib_cuda_driver, name);
    if (!fn && g_lib_cuda_runtime) fn = dlsym(g_lib_cuda_runtime, name);
    if (!fn && g_lib_cudnn) fn = dlsym(g_lib_cudnn, name);
    if (!fn && g_lib_cufft) fn = dlsym(g_lib_cufft, name);
    if (!fn && g_lib_curand) fn = dlsym(g_lib_curand, name);
    if (!fn && g_lib_cusolverDn) fn = dlsym(g_lib_cusolverDn, name);
    if (!fn && g_lib_cusparse) fn = dlsym(g_lib_cusparse, name);
    if (!fn && g_lib_nvjpeg) fn = dlsym(g_lib_nvjpeg, name);
    if (!fn && g_lib_nvrtc) fn = dlsym(g_lib_nvrtc, name);
    if (fn) g_func_cache[name] = fn;
    return fn;
}

/* Total registered functions: 2654 */
/* Libraries: cublas, cublasLt, cuda_driver, cuda_runtime, cudnn, cufft, curand, cusolverDn, cusparse, nvjpeg, nvrtc */