#!/usr/bin/env python3
"""
gpushare stress test & connection validator.

Run on any client machine to verify the remote GPU connection works
and push real GPU load so you can see utilization spike on the server.

Usage:
    python stress_test.py                     # localhost
    python stress_test.py 192.168.1.100       # remote server
    python stress_test.py 192.168.1.100 --duration 30  # 30 second burn
"""

import sys
import os
import time
import struct
import socket
import argparse
import threading

# Find the python client
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "python"))
import gpushare

# ── Formatting helpers ───────────────────────────────────────────────────────

GREEN = "\033[92m"
RED = "\033[91m"
YELLOW = "\033[93m"
CYAN = "\033[96m"
BOLD = "\033[1m"
DIM = "\033[2m"
NC = "\033[0m"

def ok(msg):   print(f"  {GREEN}✓{NC} {msg}")
def fail(msg): print(f"  {RED}✗{NC} {msg}")
def info(msg): print(f"  {CYAN}→{NC} {msg}")
def warn(msg): print(f"  {YELLOW}!{NC} {msg}")

def fmt_bytes(b):
    for unit in ["B", "KB", "MB", "GB"]:
        if b < 1024:
            return f"{b:.1f} {unit}"
        b /= 1024
    return f"{b:.1f} TB"

def fmt_time(s):
    if s < 60:
        return f"{s:.1f}s"
    m, s = divmod(int(s), 60)
    return f"{m}m {s}s"

def bar(pct, width=30):
    filled = int(pct / 100 * width)
    return f"[{'█' * filled}{'░' * (width - filled)}] {pct:.0f}%"

# ── PTX kernel that burns GPU cycles ────────────────────────────────────────

# Generated by nvcc for SM 12.0 (Blackwell / RTX 5070) with CUDA 13.1
# PTX ISA 9.1 — the correct version for this GPU/toolkit combo.
# Kernel: burn_kernel(float *out, uint iterations) — FMA loop to saturate SMs.
BURN_PTX = b"""\
.version 9.1
.target sm_120
.address_size 64

.visible .entry burn_kernel(
\t.param .u64 .ptr .align 1 burn_kernel_param_0,
\t.param .u32 burn_kernel_param_1
)
{
\t.reg .pred \t%p<3>;
\t.reg .b32 \t%r<16>;
\t.reg .b64 \t%rd<5>;

\tld.param.b64 \t%rd1, [burn_kernel_param_0];
\tld.param.b32 \t%r1, [burn_kernel_param_1];
\tmov.u32 \t%r2, %ctaid.x;
\tmov.u32 \t%r3, %ntid.x;
\tmov.u32 \t%r4, %tid.x;
\tmad.lo.s32 \t%r5, %r2, %r3, %r4;
\tcvt.rn.f32.u32 \t%r15, %r5;
\tsetp.eq.s32 \t%p1, %r1, 0;
\t@%p1 bra \t$L__done;
\tneg.s32 \t%r6, %r1;

$L__loop:
\tfma.rn.f32 \t%r7, %r15, 0f3F800054, 0f3F7FFF58;
\tfma.rn.f32 \t%r8, %r7, 0f3F7FFF58, 0f3F800054;
\tfma.rn.f32 \t%r9, %r8, 0f3F800054, 0f3F7FFF58;
\tfma.rn.f32 \t%r15, %r9, 0f3F7FFF58, 0f3F800054;
\tadd.s32 \t%r6, %r6, 1;
\tsetp.ne.s32 \t%p2, %r6, 0;
\t@%p2 bra \t$L__loop;

$L__done:
\tcvta.to.global.u64 \t%rd2, %rd1;
\tmul.wide.u32 \t%rd3, %r5, 4;
\tadd.s64 \t%rd4, %rd2, %rd3;
\tst.global.b32 \t[%rd4], %r15;
\tret;

}
"""


# ── Test phases ──────────────────────────────────────────────────────────────

def phase_connect(host, port):
    """Phase 1: Connection & handshake."""
    print(f"\n{BOLD}Phase 1: Connection{NC}")
    t0 = time.perf_counter()
    try:
        gpu = gpushare.connect(host, port)
    except Exception as e:
        fail(f"Connection failed: {e}")
        return None
    latency = (time.perf_counter() - t0) * 1000
    ok(f"Connected to {host}:{port} ({latency:.1f}ms)")

    # Ping test
    times = []
    for _ in range(5):
        t0 = time.perf_counter()
        gpu.ping()
        times.append((time.perf_counter() - t0) * 1000)
    avg = sum(times) / len(times)
    mn, mx = min(times), max(times)
    ok(f"Ping: avg={avg:.2f}ms  min={mn:.2f}ms  max={mx:.2f}ms")
    return gpu


def phase_device_info(gpu):
    """Phase 2: Device query."""
    print(f"\n{BOLD}Phase 2: Device Info{NC}")
    props = gpu.device_properties()
    ok(f"GPU: {props['name']}")
    ok(f"VRAM: {props['total_mem_mb']:.0f} MB")
    ok(f"Compute: SM {props['major']}.{props['minor']}  |  {props['multi_processor_count']} SMs  |  {props['max_threads_per_block']} threads/block")
    return props


def phase_memory(gpu):
    """Phase 3: Memory allocation & transfer."""
    print(f"\n{BOLD}Phase 3: Memory & Transfer{NC}")
    import numpy as np

    # Alloc test
    sizes = [1024, 1024*1024, 16*1024*1024, 64*1024*1024]
    ptrs = []
    for sz in sizes:
        t0 = time.perf_counter()
        try:
            p = gpu.malloc(sz)
        except Exception as e:
            fail(f"malloc({fmt_bytes(sz)}) failed: {e}")
            continue
        elapsed = (time.perf_counter() - t0) * 1000
        ok(f"malloc({fmt_bytes(sz):>10s}) → {elapsed:.2f}ms")
        ptrs.append((p, sz))

    # Transfer benchmark
    print()
    info("Transfer benchmark (H2D → D2H round-trip):")
    test_sizes = [4096, 64*1024, 1024*1024, 4*1024*1024, 16*1024*1024]
    for sz in test_sizes:
        data = np.random.randn(sz // 4).astype(np.float32)
        d = gpu.malloc(sz)

        # H2D
        t0 = time.perf_counter()
        gpu.memcpy_h2d(d, data)
        h2d_time = time.perf_counter() - t0
        h2d_bw = sz / h2d_time / 1e6

        # D2H
        result = np.empty_like(data)
        t0 = time.perf_counter()
        gpu.memcpy_d2h(result, d, sz)
        d2h_time = time.perf_counter() - t0
        d2h_bw = sz / d2h_time / 1e6

        # Verify
        match = np.allclose(data, result)
        status = f"{GREEN}verified{NC}" if match else f"{RED}MISMATCH{NC}"

        ok(f"{fmt_bytes(sz):>10s}  H2D: {h2d_bw:>7.1f} MB/s ({h2d_time*1000:>6.1f}ms)  "
           f"D2H: {d2h_bw:>7.1f} MB/s ({d2h_time*1000:>6.1f}ms)  [{status}]")
        gpu.free(d)

    # Cleanup
    for p, _ in ptrs:
        gpu.free(p)


def phase_compute_burn(gpu, duration, props):
    """Phase 4: GPU compute stress — burns the GPU for `duration` seconds."""
    print(f"\n{BOLD}Phase 4: GPU Compute Stress ({duration}s){NC}")
    import numpy as np

    # Try to load the PTX burn kernel
    try:
        mod = gpu.load_module(BURN_PTX)
        func = gpu.get_function(mod, "burn_kernel")
        has_kernel = True
        ok("Loaded burn kernel (PTX)")
    except Exception as e:
        has_kernel = False
        warn(f"PTX kernel load failed ({e}) — falling back to memory-burn stress")

    # Allocate working memory (use ~25% of VRAM)
    vram_mb = props.get("total_mem_mb", 4096)
    alloc_mb = min(int(vram_mb * 0.25), 2048)
    alloc_bytes = alloc_mb * 1024 * 1024
    info(f"Allocating {alloc_mb} MB GPU memory...")

    d_buf = gpu.malloc(alloc_bytes)
    ok(f"Allocated {alloc_mb} MB on remote GPU")

    # Generate host data
    host_data = np.random.randn(alloc_bytes // 4).astype(np.float32)

    info(f"Burning GPU for {duration} seconds — check server dashboard/nvidia-smi!")
    print()

    t_start = time.perf_counter()
    ops = 0
    bytes_transferred = 0
    last_print = 0

    # Spinner
    spinner = "⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏"

    while True:
        elapsed = time.perf_counter() - t_start
        remaining = duration - elapsed
        if remaining <= 0:
            break

        # If we have the kernel, launch it to burn compute
        if has_kernel:
            iterations = 500000  # enough FMA ops to keep GPU busy
            # Pack args: pointer (u64) + iterations (u32)
            arg_ptr = struct.pack("<Q", d_buf)
            arg_iter = struct.pack("<I", iterations)
            try:
                gpu.launch_kernel(
                    func,
                    grid=(256, 1, 1),
                    block=(256, 1, 1),
                    args=[arg_ptr, arg_iter],
                )
                ops += 1
            except Exception:
                pass

        # Also do memory transfers to drive bandwidth
        chunk = min(4 * 1024 * 1024, alloc_bytes)  # 4MB chunks
        chunk_data = host_data[:chunk // 4]
        gpu.memcpy_h2d(d_buf, chunk_data)
        gpu.memcpy_d2h(np.empty(chunk // 4, dtype=np.float32), d_buf, chunk)
        bytes_transferred += chunk * 2
        ops += 2

        gpu.synchronize()
        ops += 1

        # Progress display (update every 0.5s)
        if elapsed - last_print >= 0.5:
            last_print = elapsed
            pct = elapsed / duration * 100
            s = spinner[int(elapsed * 8) % len(spinner)]
            ops_sec = ops / max(elapsed, 0.001)
            bw = bytes_transferred / max(elapsed, 0.001) / 1e6
            sys.stdout.write(
                f"\r  {s} {bar(pct)}  "
                f"{fmt_time(elapsed)}/{fmt_time(duration)}  "
                f"{ops_sec:.0f} ops/s  {bw:.0f} MB/s  "
            )
            sys.stdout.flush()

    elapsed = time.perf_counter() - t_start
    sys.stdout.write("\r" + " " * 100 + "\r")  # clear line
    sys.stdout.flush()

    gpu.synchronize()
    gpu.free(d_buf)

    ops_sec = ops / max(elapsed, 0.001)
    bw = bytes_transferred / max(elapsed, 0.001) / 1e6
    ok(f"Burn complete: {elapsed:.1f}s, {ops} ops ({ops_sec:.0f}/s), {fmt_bytes(bytes_transferred)} transferred ({bw:.0f} MB/s)")


def phase_stats(gpu):
    """Phase 5: Server stats query."""
    print(f"\n{BOLD}Phase 5: Server Stats{NC}")
    def _recv_exact(s, n):
        buf = b""
        while len(buf) < n:
            chunk = s.recv(n - len(buf))
            if not chunk:
                return buf
            buf += chunk
        return buf

    try:
        # Use the raw protocol to query stats
        sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        sock.settimeout(5)

        host = gpu._sock.getpeername()[0]
        port = gpu._sock.getpeername()[1]
        sock.connect((host, port))

        # Init handshake
        hdr = struct.pack("<IIIHH", 0x47505553, 24, 1, 0x0001, 0)
        sock.sendall(hdr + struct.pack("<II", 1, 1))
        # Read full init response (16 byte header + 12 byte payload)
        init_resp = _recv_exact(sock, 28)

        # Stats request
        hdr = struct.pack("<IIIHH", 0x47505553, 16, 2, 0x0060, 0)
        sock.sendall(hdr)

        # Read response header
        resp_hdr = _recv_exact(sock, 16)
        magic, length, rid, opcode, flags = struct.unpack("<IIIHH", resp_hdr)
        remain = length - 16
        payload = _recv_exact(sock, remain)

        # Close
        hdr = struct.pack("<IIIHH", 0x47505553, 16, 3, 0x0002, 0)
        sock.sendall(hdr)
        sock.close()

        # Parse stats header
        uptime, total_ops, bytes_in, bytes_out, alloc, active, total_conn, num_clients = \
            struct.unpack_from("<QQQQQIII", payload, 0)

        ok(f"Server uptime: {fmt_time(uptime)}")
        ok(f"Total operations: {total_ops:,}")
        ok(f"Total data in: {fmt_bytes(bytes_in)}  |  out: {fmt_bytes(bytes_out)}")
        ok(f"GPU memory allocated: {fmt_bytes(alloc)}")
        ok(f"Active clients: {active}  |  Total connections: {total_conn}")

        # Parse per-client stats
        cl_fmt = "<I64sQQQQQ"
        cl_size = struct.calcsize(cl_fmt)
        hdr_size = struct.calcsize("<QQQQQIII")
        if num_clients > 0:
            print()
            info("Connected clients:")
            for i in range(num_clients):
                off = hdr_size + i * cl_size
                if off + cl_size > len(payload):
                    break
                sid, addr_raw, mem, ops, bi, bo, conn_s = struct.unpack_from(cl_fmt, payload, off)
                addr = addr_raw.split(b"\x00")[0].decode()
                print(f"    Session {sid}: {addr}  mem={fmt_bytes(mem)}  ops={ops:,}  "
                      f"in={fmt_bytes(bi)}  out={fmt_bytes(bo)}  uptime={fmt_time(conn_s)}")

    except Exception as e:
        warn(f"Could not query server stats: {e}")


# ── Config file reading ──────────────────────────────────────────────────────

def read_server_from_config():
    """Read server address from gpushare client config files."""
    import platform
    candidates = []
    home = os.path.expanduser("~")

    if platform.system() == "Windows":
        appdata = os.environ.get("LOCALAPPDATA", "")
        if appdata:
            candidates.append(os.path.join(appdata, "gpushare", "client.conf"))
        candidates.append(r"C:\ProgramData\gpushare\client.conf")
    else:
        candidates.append(os.path.join(home, ".config", "gpushare", "client.conf"))
        candidates.append("/etc/gpushare/client.conf")

    for path in candidates:
        if os.path.isfile(path):
            try:
                with open(path) as f:
                    for line in f:
                        line = line.strip()
                        if line.startswith("server="):
                            addr = line[7:].strip()
                            if addr:
                                return addr, path
            except Exception:
                pass
    return None, None


# ── Main ─────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="gpushare stress test & connection validator",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python stress_test.py                        # auto-detect from config
  python stress_test.py 192.168.1.100          # test remote server
  python stress_test.py 10.0.0.5 --duration 60 # 60 second GPU burn
  python stress_test.py 10.0.0.5 --quick       # fast connection check only
"""
    )
    parser.add_argument("server", nargs="?", default=None,
                        help="Server address (host or host:port). "
                             "If omitted, reads from config file.")
    parser.add_argument("--port", type=int, default=None,
                        help="Server port (default: 9847)")
    parser.add_argument("--duration", type=int, default=15,
                        help="GPU burn duration in seconds (default: 15)")
    parser.add_argument("--quick", action="store_true",
                        help="Quick mode: connection + info only, no stress test")
    args = parser.parse_args()

    # Resolve server address: arg > config > localhost
    host = args.server
    port = args.port
    config_path = None

    if host is None:
        # Try to read from config file
        config_addr, config_path = read_server_from_config()
        if config_addr:
            host = config_addr
            info(f"Server from config ({config_path}): {host}")
        else:
            host = "localhost"

    if ":" in host and port is None:
        host, port_str = host.rsplit(":", 1)
        port = int(port_str)
    if port is None:
        port = 9847

    print(f"\n{BOLD}{'═' * 55}{NC}")
    print(f"{BOLD}  gpushare Stress Test & Connection Validator{NC}")
    print(f"{BOLD}{'═' * 55}{NC}")
    print(f"  Target: {CYAN}{host}:{port}{NC}  |  Duration: {args.duration}s")
    if args.quick:
        print(f"  Mode: {YELLOW}Quick (no stress){NC}")

    # Phase 1: Connect
    gpu = phase_connect(host, port)
    if gpu is None:
        print(f"\n{RED}{BOLD}  CONNECTION FAILED{NC}")
        print(f"  Check that gpushare-server is running on {host}:{port}")
        print(f"  and that the firewall allows TCP port {port}")
        sys.exit(1)

    # Phase 2: Device info
    props = phase_device_info(gpu)

    # Phase 3: Memory & transfer
    phase_memory(gpu)

    # Phase 4: Compute burn (unless --quick)
    if not args.quick:
        phase_compute_burn(gpu, args.duration, props)
    else:
        print(f"\n{DIM}  Skipping stress test (--quick){NC}")

    # Phase 5: Stats
    phase_stats(gpu)

    # Final report
    gpu.close()
    print(f"\n{BOLD}{'═' * 55}{NC}")
    print(f"{GREEN}{BOLD}  ALL CHECKS PASSED{NC}")
    print(f"{BOLD}{'═' * 55}{NC}")
    print(f"  Remote GPU {CYAN}{props['name']}{NC} is fully operational.")
    if not args.quick:
        print(f"  Check your server's nvidia-smi or dashboard for the usage spike.")
    print()


if __name__ == "__main__":
    main()
